baseURL = 'https://blog.oygza.cc'
languageCode = 'zh-CN'
title = 'oygza'
theme = 'mini'
defaultContentLanguage= 'zh'

paginate = 10
hasCJKLanguage= true


[markup]
 [markup.highlight]
   guessSyntax = true
   style = 'friendly'
 [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
 [markup.goldmark]
   [markup.goldmark.renderer]
     unsafe = true

[social]
  github = 'https://github.com/oygza/'


[params]
  github = 'https://github.com/oygza'
  avatar = 'https://f1.oygza.com/image/avatar.jpg'
  bio = ' '
  author = 'oygza'
  copyright = '© Copyright 2021 oygza'
