baseURL = 'https://blog.oygza.cc/'
languageCode = 'zh-CN'
title = 'oygza'
theme = 'smigle'
summaryLength = 2

[menu]
  [[menu.main]]
    identifier = 'home'
    name = '首页'
    url = '/'
    weight = 1
  [[menu.main]]
    identifier = 'about'
    name = 'About Me'
    url = 'https://github.com/oygza'
    weight = 5
  [[menu.main]]
    identifier = 'posts'
    name = '文章'
    url = '/posts/'
    weight = 4
  [[menu.main]]
    identifier = 'categories'
    name = '分类'
    url = '/categories/'
    weight = 2
  [[menu.main]]
    identifier = 'tags'
    name = '标签'
    url = '/tags/'
    weight = 3


[params]
  abbrDateFmt = 'Jan 2'
  author = 'oygza'
  brandIconFile = 'http://static-file.oygza.com/mmexport1483959269310.jpg'
  dateFmt = '2006-01-02'
  subtitle = " "
